# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ProtobufLog.Sample" do
    optional :run, :bool, 1
    optional :group, :string, 2
    optional :name, :string, 3
    optional :age, :int32, 4
  end
end

module ProtobufLog
  Sample = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtobufLog.Sample").msgclass
end
